// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "/wails/runtime.js";

/**
 * Sample mirrors a protoc-gen-go-generated message, carrying both
 * protobuf and json tags. The bindings generator's FieldNameTag option
 * chooses which tag wins.
 */
export class Sample {
    declare "user_id"?: string;
    declare "full_name"?: string;
    declare "is_active"?: boolean;
    declare "status"?: number;

    /**
     * PlainGoField has no protobuf tag; its json tag is used in both modes.
     */
    declare "plain_go_field"?: string;

    /** Creates a new Sample instance. */
    constructor($$source: Partial<Sample> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Sample instance from a string or object.
     */
    static createFrom($$source: any = {}): Sample {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Sample($$parsedSource as Partial<Sample>);
    }
}
