// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Sample mirrors a protoc-gen-go-generated message, carrying both
 * protobuf and json tags. The bindings generator's FieldNameTag option
 * chooses which tag wins.
 */
export interface Sample {
    "user_id"?: string;
    "full_name"?: string;
    "is_active"?: boolean;
    "status"?: number;

    /**
     * PlainGoField has no protobuf tag; its json tag is used in both modes.
     */
    "plain_go_field"?: string;
}
